---
# host: kvm_host
# vars: zk_kvm

- name: Install some packages
  become: true
  ansible.builtin.apt:
    pkg:
      - bridge-utils
      - libguestfs-tools
      - libvirt-clients
      - libvirt-daemon
      - libvirt-daemon-system
      - python3
      - python3-libvirt
      - python3-lxml
      - qemu-kvm
      - virtinst

- ansible.builtin.set_fact:
    repository_dir: "{{ zk_kvm.data_dir }}/repository"
    images_dir: "{{ zk_kvm.data_dir }}/golden_images"
    tmp_dir: "{{ zk_kvm.data_dir }}/tmp"

- name: Ensure repository, golden_images and tmp directories exist under data_dir/
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ images_dir }}"
    - "{{ repository_dir }}"
    - "{{ tmp_dir }}"

- name: Build golden image
  ansible.builtin.include_tasks: ./build_golden_image/main.yml
  vars:
    golden_image_path: "{{ images_dir }}/{{ image.name }}/image.qcow2"
    metadata_json_path: "{{ images_dir }}/{{ image.name }}/metadata.json"
    intermediate_image_path: "{{ tmp_dir }}/{{ image.name }}-intermediate-{{ current_timestamp }}.qcow2"
  loop: "{{ zk_kvm.images }}"
  loop_control:
    loop_var: image
