---
# host: kvm_host
# vars: image, zk_kvm,
#       golden_image_path, intermediate_image_path, base_image_download_path


- block:

    - name: (build_image) qemu-img convert to intermediate qcow2 image
      become: true
      ansible.builtin.command: qemu-img convert -O qcow2 "{{ base_image_download_path }}" "{{ intermediate_image_path }}"

    - name: (build_image) copy over firstboot_script.sh
      become: true
      ansible.builtin.copy:
        content: "{{ image.firstboot_script }}"
        dest: "{{ tmp_dir }}/firstboot_script.sh"

    - name: (build_image) virt-customize intermediate image
      become: true
      ansible.builtin.command: |
        virt-customize -a {{ intermediate_image_path }} \
        --uninstall "{{ image.uninstall_packages }}" \
        --install "{{ image.install_packages }}"
        --truncate /etc/machine-id
        --firstboot {{ tmp_dir }}/firstboot_script.sh

    - name: (build_image) move intermediate image to golden image
      become: true
      ansible.builtin.command: mv {{ intermediate_image_path }} {{ golden_image_path }}
      register: mv_result
      changed_when: mv_result.rc == 0
      check_mode: false

  always:
    - name: Delete intermediate image
      become: true
      ansible.builtin.file:
        path: "{{ intermediate_image_path }}"
        state: absent
