---
# host: kvm_host
# vars: zk_kvm

- name: Install packages
  become: true
  ansible.builtin.apt:
    pkg:
      - bridge-utils
      - libguestfs-tools
      - libvirt-clients
      - libvirt-daemon
      - libvirt-daemon-system
      - python3
      - python3-libvirt
      - qemu-kvm
      - virtinst

- ansible.builtin.set_fact:
    repository_dir: "{{ zk_kvm.data_dir }}/repository"
    images_dir: "{{ zk_kvm.data_dir }}/golden_images"
    tmp_dir: "{{ zk_kvm.data_dir }}/tmp"

- name: Ensure repository, golden_images and tmp directories exist under data_dir
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ images_dir }}"
    - "{{ repository_dir }}"
    - "{{ tmp_dir }}"

- name: Get list of existing files under repository/
  ansible.builtin.find:
    paths: "{{ repository_dir }}"
    file_type: file
    recurse: false
  register: existing_images_find

- set_fact:
    required_image_names: "{{ zk_kvm.images | selectattr('name', 'in', zk_kvm.vms | map(attribute='image') | unique | list) | map(attribute='name') }}"
    existing_image_names: "{{ existing_images_find.files | default([]) | map(attribute='path') | select('match', '.*\\.img$') | map('regex_replace', '^.*\\/([^\\/]+)\\.img$', '\\1') | list }}"
    existing_image_jsons: "{{ existing_images_find.files | default([]) | map(attribute='path') | select('match', '.*\\.json$') | map('regex_replace', '^.*\\/([^\\/]+)\\.json$', '\\1') | list }}"

- name: Start async download of base images
  become: true
  ansible.builtin.get_url:
    url: "{{ image.url }}"
    dest: "{{ repository_dir }}/{{ image.name }}.img"
    checksum: "{{ image.checksum }}"
  loop: >-
      {{
        zk_kvm.images
          if not zk_kvm_images_build_only_required_images and zk_kvm_images_download_force else
        zk_kvm.images | selectattr('name', 'in', required_image_names)
          if zk_kvm_images_build_only_required_images and zk_kvm_images_download_force else
        zk_kvm.images | selectattr('name', 'in', required_image_names) | rejectattr('name', 'in', existing_image_names)
          if zk_kvm_images_build_only_required_images and not zk_kvm_images_download_force else
        zk_kvm.images | rejectattr('name', 'in', existing_image_names)
          if not zk_kvm_images_build_only_required_images and not zk_kvm_images_download_force
      }}
  loop_control:
    loop_var: image
  async: 600
  poll: 0
  register: download_jobs
  changed_when: false

- name: Wait for base image downloads to complete
  become: true
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: download_jobs_status
  until: download_jobs_status.finished
  loop: "{{ download_jobs.results }}"
  retries: "{{ zk_kvm_images_download_timeout }}"
  ignore_errors: "{{ zk_kvm_images_download_ignore_errors }}"
  delay: 1

- name: Set fact for image changed status
  become: true
  set_fact:
    image_download_changed_status: "{{ image_download_changed_status | default({}) | combine({item.item.image.name: item.changed}) }}"
  loop: "{{ download_jobs_status.results }}"

- name: Read image json contents
  become: true
  ansible.builtin.slurp:
    src: "{{ repository_dir }}/{{ image.name }}.json"
  loop: >-
    {{
      zk_kvm.images | selectattr('name', 'in', existing_image_jsons) | selectattr('name', 'in', required_image_names) 
        if zk_kvm_images_build_only_required_images else
      zk_kvm.images | selectattr('name', 'in', existing_image_jsons)
    }}
  loop_control:
    loop_var: image
  register: image_json_slurps

- name: Determine if golden image rebuild is needed
  ansible.builtin.set_fact:
    build_image: >-
      {{
        build_image | default({}) | combine({
          image.name: (
            (not zk_kvm_images_build_only_required_images or image.name in required_image_names)
            and
            (
              (image_download_changed_status is defined and image_download_changed_status[image.name])
              or
              image.name not in existing_image_jsons
              or
              image_json_slurps.results | selectattr('image.name', 'equalto', image.name) | map(attribute='content') | first | b64decode | from_json != image
            )
          )
        })
      }}
  loop: "{{ zk_kvm.images }}"
  loop_control:
    loop_var: image

- name: Build golden image
  ansible.builtin.include_tasks: ./build_templates/main.yml
  vars:
    golden_image_path: "{{ images_dir }}/{{ image.name }}.qcow2"
    intermediate_image_path: "{{ tmp_dir }}/{{ image.name }}-intermediate-{{ current_timestamp }}.qcow2"
    base_image_download_path: "{{ repository_dir }}/{{ image.name }}.img"
  loop: "{{ zk_kvm.images }}"
  loop_control:
    loop_var: image
  when: build_image[image.name] | default(false)
