---
# VM hostname; if zk_vm_hostname == "", hostname will remain unchanged
zk_vm_hostname: "{{ zk_vm_name }}"
zk_vm_networks: []
zk_vm_disks: []
zk_vm_users: []
zk_vm_post_setup_script: ""
zk_vm_post_setup_script_timeout: 10
zk_kvm_networks: []
zk_kvm_image_download_timeout: 900
zk_kvm_images:
  - name: debian12
    url: https://cdimage.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-amd64-daily.qcow2
    checksum: sha512:https://cdimage.debian.org/images/cloud/bookworm/daily/latest/SHA512SUMS
    build_template: debian
    uninstall_packages: cloud-init
    install_packages: netplan.io,qemu-guest-agent,ncurses-term
    firstboot_script: |
      #!/bin/bash
      DEBIAN_FRONTEND=noninteractive dpkg-reconfigure openssh-server
      /etc/init.d/ssh restart
      rm -rf /etc/network/*
      echo "allow-hotplug *" > /etc/network/interfaces
      netplan generate
      systemctl enable systemd-resolved.service && systemctl restart systemd-resolved.service
      systemctl enable qemu-guest-agent && systemctl start qemu-guest-agent
      growpart /dev/vda 1 && resize2fs /dev/vda1
  - name: debian11
    url: https://cdimage.debian.org/images/cloud/bullseye/daily/latest/debian-11-generic-amd64-daily.qcow2
    checksum: sha512:https://cdimage.debian.org/images/cloud/bullseye/daily/latest/SHA512SUMS
    build_template: debian
    uninstall_packages: cloud-init
    install_packages: netplan.io,qemu-guest-agent,ncurses-term
    firstboot_script: |
      #!/bin/bash
      DEBIAN_FRONTEND=noninteractive dpkg-reconfigure openssh-server
      /etc/init.d/ssh restart
      rm -rf /etc/network/*
      echo "allow-hotplug *" > /etc/network/interfaces
      netplan generate
      systemctl enable systemd-resolved.service && systemctl restart systemd-resolved.service
      systemctl enable qemu-guest-agent && systemctl start qemu-guest-agent
      growpart /dev/vda 1 && resize2fs /dev/vda1
  - name: ubuntu2204
    url: https://cloud-images.ubuntu.com/daily/server/jammy/current/jammy-server-cloudimg-amd64.img
    checksum: sha256:https://cloud-images.ubuntu.com/jammy/current/SHA256SUMS
    build_template: debian
    uninstall_packages: cloud-init
    install_packages: netplan.io,qemu-guest-agent
    firstboot_script: |
      #!/bin/bash
      DEBIAN_FRONTEND=noninteractive dpkg-reconfigure openssh-server
      /etc/init.d/ssh restart
      rm -rf /etc/network/*
      echo "allow-hotplug *" > /etc/network/interfaces
      netplan generate
      systemctl enable systemd-resolved.service && systemctl restart systemd-resolved.service
      systemctl enable qemu-guest-agent && systemctl start qemu-guest-agent
      growpart /dev/vda 1 && resize2fs /dev/vda1

zk_vm_prune_dangling_networks: true
zk_vm_prune_dangling_disks: true
zk_vm_qemu_machine_type: pc-q35-6.2
zk_vm_disk_default_zfs_properties:
  volblocksize: 128k
