---
# VM hostname; if zk_vm_hostname == "", hostname will remain unchanged
zk_vm_hostname: "{{ zk_vm_name }}"
zk_vm_networks: []
zk_vm_networks_netplan_enabled: true
zk_vm_disks: []
zk_vm_default_users: []
zk_vm_users: []
zk_vm_post_setup_script: ""
zk_vm_post_setup_script_timeout: 10
zk_kvm_networks: []
zk_kvm_images_download_timeout: 900
zk_kvm_images_download_ignore_errors: false
zk_kvm_images_download_force: false
zk_kvm_images:
  - name: rocky9
    url: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
    # checksum: sha256:https://dl.rockylinux.org/pub/rocky/9/images/x86_64/CHECKSUM # invalid format
    checksum: ""
    virt_customize_run_command: 'echo SELINUX=disabled > /etc/sysconfig/selinux && sed -i "s/^BLOCK_RPCS=.*/BLOCK_RPCS=/" /etc/sysconfig/qemu-ga'
    virt_customize_uninstall_packages: cloud-init
    virt_customize_install_packages: qemu-guest-agent,NetworkManager-config-server
  - name: opensuse_leap
    url: https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.6/images/openSUSE-Leap-15.6.x86_64-NoCloud.qcow2
    # checksum: sha256:https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.6/images/openSUSE-Leap-15.6.x86_64-NoCloud.qcow2.sha256 # wrong value
    checksum: ""
    virt_customize_uninstall_packages: cloud-init
    # virt_customize_install_packages: qemu-guest-agent
    virt_customize_firstboot: |
      #!/bin/bash
      systemctl enable qemu-guest-agent && systemctl start qemu-guest-agent
      growpart /dev/vda 1 && resize2fs /dev/vda1
  - name: debian12
    url: https://cdimage.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-amd64-daily.qcow2
    checksum: sha512:https://cdimage.debian.org/images/cloud/bookworm/daily/latest/SHA512SUMS
    virt_customize_uninstall_packages: cloud-init
    virt_customize_install_packages: netplan.io,qemu-guest-agent,ncurses-term
    virt_customize_firstboot: |
      #!/bin/bash
      DEBIAN_FRONTEND=noninteractive dpkg-reconfigure openssh-server
      /etc/init.d/ssh restart
      rm -rf /etc/network/*
      echo "allow-hotplug *" > /etc/network/interfaces
      netplan generate
      systemctl enable systemd-resolved.service && systemctl restart systemd-resolved.service
      systemctl enable qemu-guest-agent && systemctl start qemu-guest-agent
      growpart /dev/vda 1 && resize2fs /dev/vda1
  - name: debian11
    url: https://cdimage.debian.org/images/cloud/bullseye/daily/latest/debian-11-generic-amd64-daily.qcow2
    checksum: sha512:https://cdimage.debian.org/images/cloud/bullseye/daily/latest/SHA512SUMS
    virt_customize_uninstall_packages: cloud-init
    virt_customize_install_packages: netplan.io,qemu-guest-agent,ncurses-term
    virt_customize_firstboot: |
      #!/bin/bash
      DEBIAN_FRONTEND=noninteractive dpkg-reconfigure openssh-server
      /etc/init.d/ssh restart
      rm -rf /etc/network/*
      echo "allow-hotplug *" > /etc/network/interfaces
      netplan generate
      systemctl enable systemd-resolved.service && systemctl restart systemd-resolved.service
      systemctl enable qemu-guest-agent && systemctl start qemu-guest-agent
      growpart /dev/vda 1 && resize2fs /dev/vda1
  - name: ubuntu2204
    url: https://cloud-images.ubuntu.com/daily/server/jammy/current/jammy-server-cloudimg-amd64.img
    checksum: sha256:https://cloud-images.ubuntu.com/jammy/current/SHA256SUMS
    virt_customize_uninstall_packages: cloud-init
    virt_customize_install_packages: netplan.io,qemu-guest-agent
    virt_customize_firstboot: |
      #!/bin/bash
      DEBIAN_FRONTEND=noninteractive dpkg-reconfigure openssh-server
      /etc/init.d/ssh restart
      rm -rf /etc/network/*
      echo "allow-hotplug *" > /etc/network/interfaces
      netplan generate
      systemctl enable systemd-resolved.service && systemctl restart systemd-resolved.service
      systemctl enable qemu-guest-agent && systemctl start qemu-guest-agent
      growpart /dev/vda 1 && resize2fs /dev/vda1

zk_vm_prune_dangling_networks: true
zk_vm_prune_dangling_disks: true
zk_vm_qemu_machine_type: pc-q35-6.2
zk_vm_disk_default_zfs_properties:
  volblocksize: 128k
