---
namespace: karlivory
name: zk
description: Provision zfs-based kvm virtual machines on kvm hosts
version: 1.0.0
readme: README.md
authors: []
license:
  - MIT
license_file: 'LICENSE'
tags: []
dependencies: {}
repository: https://github.com/karlivory/ansible-zfs-kvm
documentation: https://github.com/karlivory/ansible-zfs-kvm/tree/main/README.md
issues: https://github.com/karlivory/ansible-zfs-kvm/issues
build_ignore:
  - '*.tar.gz'
  - .cache
  - .git
  - .gitignore
  - .pylintrc
  - .yamllint
  - __pycache__
  - docs
  - examples
  - pyrightconfig.json
  - renovate.json
  - run-tests.sh
  - tests
  - tools
  - venv
