---
# host: kvm_host
# vars: image, zk_kvm

- name: Ensure image directory exists in golden_image dir
  become: true
  ansible.builtin.file:
    path: "{{ images_dir }}/{{ image.name }}"
    state: directory

- block:
    - name: Build golden image
      become: true
      ansible.builtin.import_tasks: ./{{ image.name }}/main.yml
  rescue:
    - name: Delete intermediate image on failure
      become: true
      ansible.builtin.file:
        path: "{{ intermediate_image_path }}"
        state: absent
