---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
platforms:
  - name: test1
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 2
  inventory:
    links:
      hosts: inventory.yml

scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - converge
    # - destroy

verifier:
  name: ansible
lint: |
  ansible-lint --exclude molecule/default/
