---
# vars: kvm_host

- name: Obtain list of libvirt vms for kvm_host
  community.libvirt.virt:
    command: list_vms
  register: virt_list_vms
  changed_when: false

- name: Get info about zfs volume
  community.general.zfs_facts:
    name: "{{ zk_kvm.zvol_parent }}"
    depth: 1
    recurse: true
    type: volume
  register: zfs_facts

- set_fact:
    zk_info: >
      {{
        zk_info | default({}) | combine({
          'virt_list_vms': virt_list_vms.list_vms,
          'zvol_parent_volumes': zfs_facts.ansible_facts.ansible_zfs_datasets
        })
      }}
