---
# host: kvm_host
# vars: vm, zk_kvm

- ansible.builtin.set_fact:
    vm_tmp_dir: "{{ zk_kvm.data_dir }}/tmp/{{ vm.name }}"

- name: Get domain xml
  become: true
  ansible.builtin.command: virsh dumpxml "{{ vm.name }}"
  register: vm_virsh_dumpxml
  changed_when: false

- name: Compare vm state
  karlivory.zk.compare_vm_state:
    dumpxml: "{{ vm_virsh_dumpxml.stdout }}"
    vm: "{{ vm }}"
  register: vm_diff

- name: Set vm hostname, ensure /etc/hosts has entry
  become: true
  when: vm.hostname | length > 0
  karlivory.zk.qemu_guest_run_cmd:
    domain: "{{ vm.name }}"
    command: |
      #!/bin/bash
      if [[ "$(hostname)" != "{{ vm.hostname }}" ]]; then
        hostnamectl set-hostname "{{ vm.hostname }}"
        echo "HOSTNAME_CHANGED"
      fi
      if ! grep -q "127.0.0.1 {{ vm.hostname }}" /etc/hosts; then
        echo "127.0.0.1 {{ vm.hostname }}" >> /etc/hosts
        echo "HOSTNAME_ENTRY_ADDED"
      fi
    timeout: 10
    poll: !!float "0.1"
  register: hostname_result
  changed_when: "'HOSTNAME_CHANGED' in hostname_result.output.stdout or 'HOSTNAME_ENTRY_ADDED' in hostname_result.output.stdout"

- ansible.builtin.include_tasks: ./disks/main.yml
- ansible.builtin.include_tasks: ./networks/main.yml
- ansible.builtin.include_tasks: ./users/main.yml

- name: Update vm memory
  become: true
  when: vm_diff.output.update_memory
  ansible.builtin.command: virsh setmem --domain "{{ vm.name }}" "{{ vm.memory_mb }}M" --live --config

- name: Update vm vcpus (needs restart)
  become: true
  when: vm_diff.output.update_vcpus
  ansible.builtin.shell: virsh setvcpus --domain "{{ vm.name }}" "{{ vm.vcpus }}" --maximum --config && virsh setvcpus --domain "{{ vm.name }}" "{{ vm.vcpus }}" --config
