---
- ansible.builtin.set_fact:
    current_timestamp: "{{ lookup('pipe', 'date +%s%N') }}"
  when: current_timestamp is not defined
  connection: local
  run_once: true

- name: Gather info from kvm host
  ansible.builtin.include_tasks: ./01_get_info.yml
  when:
    - inventory_hostname in groups['zk_kvm_hosts']

- name: Create vm
  ansible.builtin.include_tasks: ./02_define_domain.yml
  loop: "{{ zk_kvm.vms }}"
  loop_control:
    loop_var: vm
  when:
    - inventory_hostname in groups['zk_kvm_hosts']

- name: Wait for qemu-guest-agent
  ansible.builtin.include_tasks: ./wait_for_qemu_agent.yml
  loop: "{{ zk_kvm.vms }}"
  loop_control:
    loop_var: vm
  when:
    - inventory_hostname in groups['zk_kvm_hosts']

- name: Set up vm networks, disks
  ansible.builtin.include_tasks: ./03_vm_setup.yml
  loop: "{{ zk_kvm.vms }}"
  loop_control:
    loop_var: vm
  when:
    - inventory_hostname in groups['zk_kvm_hosts']
