---
# host: kvm_host
# vars: vm

- ansible.builtin.set_fact:
    vm_tmp_dir: "{{ zk_kvm.data_dir }}/tmp/{{ vm.name }}"

- block:
    - name: Create vm
      ansible.builtin.include_tasks: ./02_define_domain.yml
    - name: Wait for qemu-guest-agent
      ansible.builtin.include_tasks: ./wait_for_qemu_agent.yml
    - name: Set up vm networks, disks
      ansible.builtin.include_tasks: ./03_vm_setup.yml
  always:
    - name: Cleanup tmp
      ansible.builtin.file:
        path: "{{ vm_tmp_dir }}"
        state: absent
