---
# host: kvm_host
# vars: vm, zk_kvm, disk, zfs_volume

- name: Create zfs volume for disk
  become: true
  community.general.zfs:
    name: "{{ zfs_volume }}"
    state: present
    extra_zfs_properties: "{{ disk.zfs.properties }}"
