---
# host: kvm_host
# vars: vm, zk_kvm, disk

- ansible.builtin.set_fact:
    zfs_volume: "{{ disk.zfs.zvol_parent }}/{{ disk.name }}"

- name: Create disk
  ansible.builtin.include_tasks: ./create_disk.yml
  when: disk_idx != 0

- name: Check domain xml whether it has a disk with matching source dev
  community.general.xml:
    xmlstring: "{{ vm_virsh_dumpxml.stdout }}"
    xpath: /domain/devices/disk/source[@dev='/dev/zvol/{{ zfs_volume }}']
    count: true
  register: xml_count
  delegate_to: localhost
  connection: local

- ansible.builtin.set_fact:
    vm_has_disk: false

- ansible.builtin.set_fact:
    vm_has_disk: "{{ xml_count.count > 0 }}"

- ansible.builtin.set_fact:
    tmp_disk_xml_path: "{{ vm_tmp_dir }}/{{ disk.name }}-disk.xml"
  when: not vm_has_disk

- name: Make disk libvirt xml template
  become: true
  when: not vm_has_disk
  ansible.builtin.template:
    src: disk.xml.j2
    dest: "{{ tmp_disk_xml_path }}"

- name: Attach disk to domain
  become: true
  when: not vm_has_disk
  ansible.builtin.command: virsh attach-device "{{ vm.name }}" "{{ tmp_disk_xml_path }}" --persistent
