---
# host: kvm_host
# vars: vm, disk

- ansible.builtin.set_fact:
    zfs_volume: "{{ disk.zfs.zvol_parent }}/{{ disk.name }}"

- name: Create disk
  ansible.builtin.include_tasks: ./create_disk.yml

- ansible.builtin.set_fact:
    tmp_disk_xml_path: "{{ vm_tmp_dir }}/{{ disk.name }}-disk.xml"

- name: Make disk libvirt xml template
  become: true
  ansible.builtin.template:
    src: disk.xml.j2
    dest: "{{ tmp_disk_xml_path }}"

- name: Attach disk to domain
  become: true
  ansible.builtin.command: virsh attach-device "{{ vm.name }}" "{{ tmp_disk_xml_path }}" --persistent
