---
# host: kvm_host
# vars: vm, zk_info, disk, zfs_volume

- ansible.builtin.set_fact:
    volume_exists: "{{ zfs_volume in zk_info.zfs_children[disk.zfs.zvol_parent] }}"

- name: Create zfs volume for disk
  when: not volume_exists
  become: true
  community.general.zfs:
    name: "{{ zfs_volume }}"
    state: present
    extra_zfs_properties: "{{ disk.zfs.properties }}"

- name: Update zk_info with the new zfs volume
  when: not volume_exists
  ansible.builtin.set_fact:
    zk_info: >-
      {{
        zk_info | combine({
          'zfs_children': {
            disk.zfs.zvol_parent: zk_info.zfs_children[disk.zfs.zvol_parent] + [zfs_volume]
          }
        }, recursive=True)
      }}
