name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up directory structure
      run: |
        mkdir -p ansible_collections/karlivory/zk
        mv ${{ github.workspace }}/* ansible_collections/karlivory/zk/
        mv ${{ github.workspace }}/.* ansible_collections/karlivory/zk/ || true

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ansible_collections/karlivory/zk/test-requirements.txt

    - name: Run unit tests
      working-directory: ./ansible_collections/karlivory/zk
      run: |
        ansible-test units --requirements

    - name: Run integration tests
      working-directory: ./ansible_collections/karlivory/zk
      run: |
        ansible-test integration

