name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up directory structure
      run: |
        mkdir -p ansible_collections/karlivory/zk
        mv ./* ansible_collections/karlivory/zk/ || true
        mv ./.* ansible_collections/karlivory/zk/ || true

    - name: Run unit tests
      run: |
        cd ./ansible_collections/karlivory/zk
        chmod 777 -R .
        # sudo apt-get update
        # sudo apt-get install virtualenv -y
        # ./run-tests.sh
        python -m pip install --upgrade pip
        pip install -r ./test-requirements.txt
        ansible-test units --requirements
        ansible-test integration

