name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Set up directory structure
      run: |
        mkdir -p ansible_collections/karlivory/zk
        mv ./* ansible_collections/karlivory/zk/ || true
        mv ./.* ansible_collections/karlivory/zk/ || true

    - name: Run unit tests
      run: |
        sudo apt-get update
        sudo apt-get install virtualenv -y
        cd ./ansible_collections/karlivory/zk
        ./run-tests.sh

