---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up directory structure
        run: |
          mkdir -p ansible_collections/karlivory/zk
          mv ./* ansible_collections/karlivory/zk/ || true
          mv ./.* ansible_collections/karlivory/zk/ || true

      - name: Run unit and integration tests
        run: |
          cd ./ansible_collections/karlivory/zk
          python -m pip install --upgrade pip
          pip install -r ./test-requirements.txt
          ansible-test units --requirements
          ansible-test integration
